# This is the configuration file for TriWeb. Use it to customize the site.

# This is the title of the website, displayed on the tab in most browsers
title: Tri Website

# Nickname for the site, this should be one word and short like TriWeb or UCDTri
title_nick: TriWeb

# This is the logo that appears in the upper left corner of the website
banner_logo: /images/triweb_logo.jpeg

# Years to include in copyright for the footer (applies only to content, not code).
content_copyright_years: 2011
